/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteForm' : IDL.Func([IDL.Nat], [], []),
  'getAllForms' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
  'getFilteredFormsByTimestamp' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FormSubmission)],
      ['query'],
    ),
  'searchFormsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FormSubmission)],
      ['query'],
    ),
  'searchFormsByServiceType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FormSubmission)],
      ['query'],
    ),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteForm' : IDL.Func([IDL.Nat], [], []),
    'getAllForms' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
    'getFilteredFormsByTimestamp' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FormSubmission)],
        ['query'],
      ),
    'searchFormsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FormSubmission)],
        ['query'],
      ),
    'searchFormsByServiceType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FormSubmission)],
        ['query'],
      ),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };